# Generated by Django 5.0.2 on 2024-12-09 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='def_pfp',
            field=models.ImageField(default='pfp/defaults/1.png', upload_to=''),
        ),
    ]
