# Generated by Django 4.2.7 on 2023-11-16 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='def_pfp',
            field=models.ImageField(default='pfp/defaults/1.png', upload_to=''),
        ),
    ]
