# Generated by Django 4.2.6 on 2023-10-30 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0002_newpost_creation_date'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NewPost',
            new_name='Post',
        ),
    ]
