# Generated by Django 4.2.6 on 2023-10-30 01:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0003_rename_newpost_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_content',
            new_name='content',
        ),
    ]
