# Generated by Django 4.2.6 on 2023-10-31 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0006_user_followers_user_following'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follower',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='user',
            name='followin',
            field=models.TextField(default=''),
        ),
    ]
