# Generated by Django 4.2.6 on 2023-10-31 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0007_user_follower_user_followin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followin',
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.TextField(default=''),
        ),
    ]
