# Generated by Django 4.2.6 on 2023-11-02 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0008_remove_user_followers_remove_user_followin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='follower',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='following',
            field=models.TextField(default='', null=True),
        ),
    ]
