# Generated by Django 4.2.7 on 2023-11-03 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0010_post_edited'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='likers',
            field=models.TextField(default='', null=True),
        ),
    ]
