# Generated by Django 4.2.7 on 2023-11-09 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0011_post_likers'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='pfp/defaults/7.png', upload_to='pfp/user'),
        ),
    ]
