# Generated by Django 4.2.7 on 2023-11-10 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0012_user_pfp'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(default='pfp/defaults/2.png', upload_to='pfp/user'),
        ),
    ]
