# Generated by Django 4.2.7 on 2023-11-16 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0014_user_def_pfp_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='def_pfp',
            field=models.ImageField(default='pfp/defaults/8.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(null=True, upload_to='pfp/user'),
        ),
    ]
