# Generated by Django 4.2.7 on 2023-11-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0015_alter_user_def_pfp_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='def_pfp',
            field=models.ImageField(default='pfp/defaults/4.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/<function User.user_name at 0x0000022C25B3B550>'),
        ),
    ]
