# Generated by Django 4.2.7 on 2023-11-16 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0016_alter_user_def_pfp_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='def_pfp',
            field=models.ImageField(default='pfp/defaults/8.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='pfp/<function User.user_name at 0x0000017DC22BB550>'),
        ),
    ]
