# Generated by Django 4.2.7 on 2023-11-16 15:26

from django.db import migrations, models
import network.models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0017_alter_user_def_pfp_alter_user_pfp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='def_pfp',
            field=models.ImageField(default='pfp/defaults/7.png', upload_to=''),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to=network.models.User.path_for_user),
        ),
    ]
